# Introduction to NumPy
### What we will cover?
* 1 Creating Single Dimensional arrays
* 2 Multidimensional array
* 3 Randomly generated arrays
* 4 Element wise operation
* 5 Summarizing operations

## Single Dimensional Arrays

In [1]:
import numpy as np

In [3]:
# Create an array with all the elements to be zero

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# Create an array with all element 1

np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
# Create an array of size 10 with all elements 3

np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
# Create an array with different elements
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [9]:
# Create an array with  range
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
# Create an array with evenly spaced numbers within a specified range
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional arrays

In [15]:
# Create a  3*3 matrix with all elements zeros
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Create square matrix with all elements one
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# create a multidimensional array with different elements
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#replace 2 with 20
arr[0][1]=20
print(arr)

#replace last row with 1
arr[2:]=1
print(arr)

# replace column 3 with 2
arr[:,2]=2
print(arr)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]
[[ 1 20  2]
 [ 4  5  2]
 [ 1  1  2]]


In [37]:
# Create a matrix 3*3 with all elements 10

np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly generated arrays

    * Numpy can create arrays filled with random numbers
    * To ensure the reproductbility , you can seed using `np.random.seed()`
    * It will generate the exact same random number for each executions.
    * If you remove or change the seed values, the sequece of random numbers will be changed.

In [61]:
# Create a matrix with random numbers
np.random.rand(5)

array([0.20012414, 0.81204355, 0.37293679, 0.80964124, 0.01199526])

In [58]:
# Create a matrix with random numbers with fixed value
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [66]:
# Create random matrix with normal distribution
np.random.randn(5,2)

array([[ 0.26319554, -0.5005371 ],
       [-1.17608777,  0.35557183],
       [-0.98776529,  0.88511882],
       [-0.18749341,  0.98134195],
       [ 0.87554546,  1.11656366]])

In [64]:
# create a matrix with random integers
np.random.randint(low=0, high=100, size=(5,2))

array([[16, 41],
       [20, 31],
       [24, 67],
       [ 8, 91],
       [46, 67]])