# Introduction to NumPy
### What we will cover?
* 1 Creating Single Dimensional arrays
* 2 Multidimensional array
* 3 Randomly generated arrays
* 4 Element wise operation
* 5 Summarizing operations

## Single Dimensional Arrays

In [1]:
import numpy as np

In [3]:
# Create an array with all the elements to be zero

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# Create an array with all element 1

np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
# Create an array of size 10 with all elements 3

np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [24]:
# Create an array with different elements
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [25]:
# Create an array with  range
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
# Create an array with evenly spaced numbers within a specified range
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional arrays

In [27]:
# Create a  3*3 matrix with all elements zeros
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# Create square matrix with all elements one
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# create a multidimensional array with different elements
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#replace 2 with 20
arr[0][1]=20
print(arr)

#replace last row with 1
arr[2:]=1
print(arr)

# replace column 3 with 2
arr[:,2]=2
print(arr)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]
[[ 1 20  2]
 [ 4  5  2]
 [ 1  1  2]]


In [30]:
# Create a matrix 3*3 with all elements 10

np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly generated arrays
 * Numpy can create arrays filled with random numbers
 * To ensure the reproductbility , you can seed using `np.random.seed()`
 * It will generate the exact same random number for each executions.
 * If you remove or change the seed values, the sequece of random numbers will be changed.


In [31]:
# Create a matrix with random numbers
np.random.rand(5)

array([0.76804173, 0.77144342, 0.87825067, 0.02008994, 0.03071942])

In [32]:
# Create a matrix with random numbers with fixed value
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [33]:
# Create random matrix with normal distribution
np.random.randn(5,2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [34]:
# create a matrix with random integers
np.random.randint(low=0, high=100, size=(5,2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])

## Element wise operation on entire arrays element by element

In [35]:
a = np.arange(5)
b = (10 + (a*2))
print(a)
print(b)

[0 1 2 3 4]
[10 12 14 16 18]


In [36]:
# Comparision operations
a==b


array([False, False, False, False, False])

In [37]:
a>=2

array([False, False,  True,  True,  True])

In [38]:
# summarizing of the data
# numpy provides function for summarizing array data

a=np.array([1,2,3,4,5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())
print(a.var())
print(a.cumsum())
print(a.cumprod())
print(a.argmax())
print(a.argmin())

1
5
15
3.0
1.4142135623730951
2.0
[ 1  3  6 10 15]
[  1   2   6  24 120]
4
0
